# Generated by Django 4.0.6 on 2022-07-11 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 7, 11, 7, 29, 20, 24659))),
                ('no_cars', models.IntegerField()),
            ],
        ),
    ]
