# Generated by Django 4.0.6 on 2022-07-11 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 7, 32, 36, 429449)),
        ),
    ]
